version: '3'
services:
   mongodb:
       image: mongo:4.0.8
       container_name: mongodb
       restart: unless-stopped
       # command: mongod --auth
       environment:
          MONGODB_DATA_DIR: /data/db
          MONDODB_LOG_DIR: /dev/null
          # MONGO_INITDB_ROOT_USERNAME: root
          #MONGO_INITDB_ROOT_PASSWORD: rootPassword
       volumes:
          - mongodbdata:/data/db
       ports:
          - "27017:27017"
            #network_mode: "host"
volumes:
    mongodbdata:
  
